name: Deploy to GithubPages Hosting on schedule
on:
  push:
  workflow_dispatch:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn && yarn build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build

          deploy_key: ${{ secrets.GITHUB_TOKEN }}
