name: Deploy to GithubPages Hosting on schedule
on:
  push:
  workflow_dispatch:
    branches: [main]

strategy:
  matrix:
    node-version: [12.x]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn && yarn build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./build

          deploy_key: ${{ secrets.GITHUB_TOKEN }}
